Task connect front back
lambdaworks/lambda-knowledge-bot pull request #19
Opened 2024-01-23 12:45 UTC by kasikovicivana

Task connect front back

2024-02-01 10:02 UTC, sonjajos commented on client/src/components/chat.tsx
> +  const reload = async () => {
I would extract this function in api.ts file since this is an API call.

2024-02-01 10:03 UTC, sonjajos commented on client/src/components/chat.tsx
> +  const append = (val: { content: string; role: string }) => {
This function also.

2024-02-01 10:06 UTC, sonjajos commented on client/src/components/clear-history.tsx
>              onClick={event => {
We could extract this function outside of JSX expression.

2024-02-01 10:06 UTC, sonjajos commented on client/src/components/header.tsx
> +  const handleLogout = async () => {
This function could also be in api file.

2024-02-01 10:07 UTC, sonjajos commented on client/src/components/header.tsx
> +    console.log(storedEmail)
Remove console.log from here too.

2024-02-01 10:08 UTC, sonjajos commented on client/src/components/header.tsx
> +      {email !== null && (
We could use just `!email` instead of `email !== null`.

2024-02-01 10:09 UTC, sonjajos commented on client/src/components/header.tsx
> +        {email !== null ? (
Also here.

2024-02-01 10:12 UTC, sonjajos commented on client/src/components/sidebar-items.tsx
> +                  removeChat={() => {
Extract this function above JSX expression too.

2024-02-01 10:12 UTC, sonjajos commented on client/src/components/sidebar-items.tsx
> +                  shareChat={() => {
This one too

2024-02-01 10:17 UTC, sonjajos commented on client/src/api/chat.service.ts
> +  console.log("LIKE")
Remove this console.log too.

2024-02-01 10:17 UTC, sonjajos commented on client/src/api/chat.service.ts
> +  console.log("DISLIKE")
This one too.

2024-02-01 10:17 UTC, sonjajos commented
### General comments and suggestions for improvements:

- Implement router
- Remove all unnecessary console logs and comments
- It would be good to have some sort of shared state (context would be ok here, maybe mobx).
- We could think of adding loaders and/or skeletons while data is loading.

2024-02-01 13:50 UTC, kasikovicivana commented on client/src/components/header.tsx
> +  const handleLogout = async () => {
This hook has to be inside the component.

2024-02-01 15:12 UTC, kasikovicivana commented on client/src/components/chat.tsx
> +  const append = (val: { content: string; role: string }) => {
I would't put this function in api file since it doesn't contain api calls for now.

2024-02-05 09:47 UTC, kasikovicivana commented on client/src/api/api.ts
> +  const relevantDocuments: Document[] = [];
Relevant documents are parsed separately and attached at the end of the bot's answer, allowing users to access them.

2024-02-05 13:54 UTC, sonjajos requested changes

2024-02-05 13:54 UTC, sonjajos commented on client/src/components/chat-share-dialog.tsx
> +              startShareTransition(async () => {
No need for curly brackets here.

2024-02-05 13:54 UTC, sonjajos commented on client/src/components/chat.tsx
> +  const { stop } = { stop: () => {
I think it would be more intuitive if you defined this function like this:
```
const stop = (): void => {
  stopGenerating();
  setIsLoading(false);
}
```

2024-02-05 13:54 UTC, sonjajos commented on client/src/api/util.ts
> +export const isEmpty = (value: string | number | object | undefined | null): boolean =>
In api folder, we should define only services that communicate with server. Please create folder `src/utils` and place `helper.ts` file there. That file should contain all helper functions that would be used in code.

For types, please add `src/types` folder and place something like `storage.ts` file there, where you would define `LocalStorageKey` and `SessionStorageKey`

2024-02-05 13:54 UTC, sonjajos commented on client/src/components/login-button.tsx
> +const emailKey = "email";
emailKey should be exported from file that stores keys for local/session storage.

2024-02-05 13:54 UTC, sonjajos commented on client/src/components/login-button.tsx
> +  const sidebarKey: LocalStorageKey = "sidebar";
Same here.

2024-02-05 13:54 UTC, sonjajos commented on client/src/api/util.ts
> +export type SessionStorageKey = "email";
This is ok, but it would be  better to export constant that will contain all session storage keys, something like:
```
export const SESSION_STORAGE_KEYS: Record<string, SessionStorageKey> = {
  EMAIL: "email",
};
```
So, if you decide to change some of the keys, you will just update their values in this constant. Also, you will just import this constant wherever you need to use it, like this:

`sessionStorage.getItem(SESSION_STORAGE_KEYS.EMAIL);`

Same thing for LocalStorageKey.

2024-02-05 14:06 UTC, kasikovicivana commented on client/src/App.tsx
> +      authorizationParams={{ redirect_uri: `${url}`}}
This syntax is required, just url doesn't work.

2024-02-05 15:15 UTC, sonjajos approved these changes

2024-02-06 14:29 UTC, merged